/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carwash_resservation_application;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author buanm
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form loginto
     */
    public Register() {
        initComponents();
        password.setEchoChar((char) 0);
        cpassword.setEchoChar((char) 0);
        error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        cpassword = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        ds = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        show = new javax.swing.JCheckBox();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));

        jPanel1.setBackground(new java.awt.Color(94, 192, 248));

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carwash_resservation_application/CC105 IMAGE/logs.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fname.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        fname.setText("First name");
        fname.setToolTipText("");
        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnameFocusGained(evt);
            }
        });
        fname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnameMouseClicked(evt);
            }
        });
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameKeyTyped(evt);
            }
        });

        lname.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        lname.setText("Last name");
        lname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnameMouseClicked(evt);
            }
        });
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        username.setText("Username");
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        email.setText("Email");
        email.setToolTipText("_@gmail.com");
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        password.setText("Password");
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        cpassword.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        cpassword.setText("Confirm Password");
        cpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpasswordMouseClicked(evt);
            }
        });
        cpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpasswordActionPerformed(evt);
            }
        });

        register.setBackground(new java.awt.Color(94, 192, 248));
        register.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        ds.setText("Already have an Account?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("REGISTER ACCOUNT");

        number.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        number.setText("Contact Number");
        number.setToolTipText("09#########");
        number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberMouseClicked(evt);
            }
        });
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(94, 192, 248));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        login.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        login.setForeground(new java.awt.Color(94, 192, 248));
        login.setText("Log in");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });

        show.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        show.setText("Show password");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        error.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        error.setForeground(java.awt.Color.red);
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error.setText("Please fill up all Information first!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(username)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lname, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                            .addComponent(email)
                            .addComponent(password)
                            .addComponent(cpassword)
                            .addComponent(number)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(ds)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(login)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ds)
                    .addComponent(login))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
        if(username.getText().equals("Username")){
            username.setText("");
        }
    }//GEN-LAST:event_usernameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
        if(email.getText().equals("Username")){
            email.setText("");
        }
    }//GEN-LAST:event_emailActionPerformed

    private void cpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpasswordActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
        if(number.getText().equals("Username")){
            number.setText("");
        }
    }//GEN-LAST:event_numberActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameFocusGained

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        try {
        // Open connection
                Class.forName("com.mysql.jdbc.Driver");
                try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carwash_reservation_db?userSSL=false", "root", "")) {
                    String fName = fname.getText();
                    String lName = lname.getText();
                    String userName = username.getText();
                    String cNum = number.getText();
                    String Email = email.getText();
                    String pass = password.getText();
                    String cpass = cpassword.getText();

                    // Check if any of the required fields are empty
                    if (fName.equals("First name") || lName.equals("Last name") || userName.equals("Username") || cNum.equals("Contact Number") || Email.equals("Email") || pass.equals("Password") || cpass.equals("Confirm Password")) {
                        error.setVisible(true);
                        error.setText("Please fill up all Information first!");
                    } else if (cNum.length() != 11){
                        error.setVisible(true);
                        error.setText("Enter a valid number");
                    } else if (!Email.contains("@gmail.com")){
                        error.setVisible(true);
                        error.setText("Enter a valid email address");
                    } else if (!pass.equals(cpass)) {
                        error.setVisible(true);
                        error.setText("Passwords do not match.");
                    }
                    else {
                            String sql = "INSERT INTO tbl_carwashreservation (first_name, last_name, user_name, email, contact_num, password) VALUES (?, ?, ?, ?, ?, ?)";
                            PreparedStatement pstmt = (PreparedStatement) con.prepareStatement(sql);
                            pstmt.setString(1, fName);
                            pstmt.setString(2, lName);
                            pstmt.setString(3, userName);
                            pstmt.setString(4, Email);
                            pstmt.setString(5, cNum);
                            pstmt.setString(6, pass);

                            // Execute the statement
                            int rowsAffected = pstmt.executeUpdate();
                            if (rowsAffected > 0) {
                                JOptionPane.showMessageDialog(null, "Registration successful.");
                                dispose(); // Close the current window
                                // Open the dashboard window
                                Login logPage = new Login();
                                logPage.setVisible(true);
                            } else {
                                JOptionPane.showMessageDialog(null, "Registration failed.");
                            }
                        }
                    
                }
            } catch(Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
    }//GEN-LAST:event_registerActionPerformed

    private void fnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnameMouseClicked
        // TODO add your handling code here:
        if(fname.getText().equals("First name")){
            fname.setText("");
        }
        
        if(lname.getText().equals("")){
            lname.setText("Last name");
        }
        
        if(username.getText().equals("")){
            username.setText("Username");
        }
        
        if(number.getText().equals("")){
            number.setText("Contact Number");
        }
        
        if(email.getText().equals("")){
            email.setText("Email");
        }
        
        if(password.getText().equals("")){
            password.setText("Password");
            password.setEchoChar((char) 0);
        }
        
        if(cpassword.getText().equals("")){
            cpassword.setText("Confirm Password");
            cpassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_fnameMouseClicked

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void lnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnameMouseClicked
        // TODO add your handling code here:
        if(lname.getText().equals("Last name")){
            lname.setText("");
        }
        
        if(fname.getText().equals("")){
            fname.setText("First name");
        }
       
        if(username.getText().equals("")){
            username.setText("Username");
        }
        
        if(number.getText().equals("")){
            number.setText("Contact Number");
        }
        
        if(email.getText().equals("")){
            email.setText("Email");
        }
        
        if(password.getText().equals("")){
            password.setText("Password");
            password.setEchoChar((char) 0);
        }
        
        if(cpassword.getText().equals("")){
            cpassword.setText("Confirm Password");
            cpassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_lnameMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        dispose();
        Login logPage = new Login();
        logPage.show();
    }//GEN-LAST:event_loginMouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
        if(username.getText().equals("Username")){
            username.setText("");
        }
        
        if(fname.getText().equals("")){
            fname.setText("First name");
        }
        
        if(lname.getText().equals("")){
            lname.setText("Last name");
        }
        
        if(number.getText().equals("")){
            number.setText("Contact Number");
        }
        
        if(email.getText().equals("")){
            email.setText("Email");
        }
        
        if(password.getText().equals("")){
            password.setText("Password");
            password.setEchoChar((char) 0);
        }
        
        if(cpassword.getText().equals("")){
            cpassword.setText("Confirm Password");
            cpassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_usernameMouseClicked

    private void numberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberMouseClicked
        // TODO add your handling code here:
        if(number.getText().equals("Contact Number")){
            number.setText("");
        }
        
        if(fname.getText().equals("")){
            fname.setText("First name");
        }
        
        if(lname.getText().equals("")){
            lname.setText("Last name");
        }
        
        if(username.getText().equals("")){
            username.setText("Username");
        }
        
        if(email.getText().equals("")){
            email.setText("Email");
        }
        
        if(password.getText().equals("")){
            password.setText("Password");
            password.setEchoChar((char) 0);
        }
        
        if(cpassword.getText().equals("")){
            cpassword.setText("Confirm Password");
            cpassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_numberMouseClicked

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
        if(email.getText().equals("Email")){
            email.setText("");
        }
        
        if(fname.getText().equals("")){
            fname.setText("First name");
        }
        
        if(lname.getText().equals("")){
            lname.setText("Last name");
        }
        
        if(username.getText().equals("")){
            username.setText("Username");
        }
        
        if(number.getText().equals("")){
            number.setText("Contact Number");
        }
        
        if(password.getText().equals("")){
            password.setText("Password");
            password.setEchoChar((char) 0);
        }
        
        if(cpassword.getText().equals("")){
            cpassword.setText("Confirm Password");
            cpassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_emailMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
        if(password.getText().equals("Password")){
            password.setText("");
            password.setEchoChar('*');
        }
        
        if(fname.getText().equals("")){
            fname.setText("First name");
        }
        
        if(lname.getText().equals("")){
            lname.setText("Last name");
        }
        
        if(username.getText().equals("")){
            username.setText("Username");
        }
        
        if(number.getText().equals("")){
            number.setText("Contact Number");
        }
        
        if(email.getText().equals("")){
            email.setText("Email");
        }
        
        if(cpassword.getText().equals("")){
            cpassword.setText("Confirm Password");
            cpassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_passwordMouseClicked

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        if (show.isSelected() && !password.getText().equals("Password") && !cpassword.getText().equals("Confirm Password")){
            password.setEchoChar((char) 0);
            cpassword.setEchoChar((char) 0);
        }else if (show.isSelected() && password.getText().equals("Password") && cpassword.getText().equals("Confirm Password")){
            password.setEchoChar((char) 0);
            cpassword.setEchoChar((char) 0);
        } else if (show.isSelected() && !password.getText().equals("Password") && cpassword.getText().equals("Confirm Password")){
            password.setEchoChar((char) 0);
        } else if (show.isSelected() && password.getText().equals("Password") && !cpassword.getText().equals("Confirm Password")){
            cpassword.setEchoChar((char) 0);
        } else if (!show.isSelected() && password.getText().equals("Password") && cpassword.getText().equals("Confirm Password")){
            password.setEchoChar((char) 0);
            cpassword.setEchoChar((char) 0);
        } else if (!show.isSelected() && !password.getText().equals("Password") && cpassword.getText().equals("Confirm Password")){
            password.setEchoChar('*');
            cpassword.setEchoChar((char) 0);
        } else if (!show.isSelected() && password.getText().equals("Password") && !cpassword.getText().equals("Confirm Password")){
            password.setEchoChar((char) 0);
            cpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showActionPerformed

    private void cpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpasswordMouseClicked
        // TODO add your handling code here:
        if(cpassword.getText().equals("Confirm Password")){
            cpassword.setText("");
            cpassword.setEchoChar('*');
        }
        
        if(fname.getText().equals("")){
            fname.setText("First name");
        }
        
        if(lname.getText().equals("")){
            lname.setText("Last name");
        }
        
        if(username.getText().equals("")){
            username.setText("Username");
        }
        
        if(number.getText().equals("")){
            number.setText("Contact Number");
        }
        
        if(email.getText().equals("")){
            email.setText("Email");
        }
        
        if(password.getText().equals("")){
            password.setText("Password");
            password.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_cpasswordMouseClicked

    private void fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyTyped
        // TODO add your handling code here:
        if (fname.getText().equals("First name")){
            fname.setText("");
        }
    }//GEN-LAST:event_fnameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cpassword;
    private javax.swing.JLabel ds;
    private javax.swing.JTextField email;
    private javax.swing.JLabel error;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel login;
    private javax.swing.JTextField number;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton register;
    private javax.swing.JCheckBox show;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
